version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    target-branch: dev
    labels:
      - dependencies
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor', 'version-update:semver-patch']
    commit-message:
      prefix: chore
      include: scope
