name: Deployment

concurrency:
  group: "lotto-{{ github.ref_name }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      CLF_DIST: ${{ vars.CLF_DIST }}
    steps:
      - name: output env variables
        run: |
          echo GITHUB_REF_NAME: $GITHUB_REF_NAME
          echo AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          echo AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          echo AWS_REGION: $AWS_REGION
          echo S3_BUCKET: $S3_BUCKET
          echo CLF_DIST: $CLF_DIST

      - name: checkout
        uses: actions/checkout@v4

      - name: install
        run: |
          yarn install

      - name: build
        run: |
          yarn build          

      - name: deploy
        run: |
          bash deploy.sh
